### ISSUE TITLE
Wrong file name for product customization

### ISSUE THREAD

**Issue by ludohenin** [PrestaShop/StarterTheme#109]
In PS, it's singular [ProductController.php#L334](https://github.com/PrestaShop/PrestaShop/blob/develop/controllers/front/ProductController.php#L334)
Where here it's plural [catalog/_partials](https://github.com/PrestaShop/StarterTheme/tree/master/templates/catalog/_partials)

Which one is correct ?

**Comment by maximebiloe** [comment]
Good catch. It should be singular.
Would you mind making a PR to rename the file, please?
