### ISSUE TITLE
There's no way to close the popup after adding product to cart

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/StarterTheme#125]
I think that closing button should be displayed :)

![image](https://cloud.githubusercontent.com/assets/2137763/18935881/4eefd5c2-85e3-11e6-9d4d-bb261f98b2bf.png)

**Comment by maximebiloe** [comment]
The closing button is not mandatory, just a click anywhere close the modal.
We just wanted to provide a really minimalistic interface.
So I close this issue but if you want to add it, you can make a PR on https://github.com/PrestaShop/ps_shoppingcart
