### ISSUE TITLE
Product available with different options, but not really

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/StarterTheme#126]
There's a weird situation, i'm not able to reproduce it every time but try this:
1. product #4
2. change combination
3. click on this popup after adding to cart, click somewhere inside content of this popup
4. right now you can't disable popup by clicking anywhere
5. refresh the page
6. boom, Product available with different options...

...even though product **is** available with this option, nothing helps, everything is wrong right now, you can't add product to cart, changing combination doesn't help etc. you need to to go Homepage, visit this product again and now you can add it to cart again.

Super weird.

Edit: i've found that this happens also when you visit product for the first time, change combination and refresh the page, after refresh we have `0 items` and `Product available with different options`.

**Comment by PierreRambaud** [comment]
This project is not maintained anymore by the core team. Theme improvements must be brought instead to the classic theme in the [PrestaShop repository](https://github.com/PrestaShop/PrestaShop).
Thanks for your understanding.
