### ISSUE TITLE
Add to cart on product list doesn't work for a product with attributes

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/StarterTheme#127]
As described in title, clicking "Add to cart" from the product on the homepage doesn't work if product has attributes, maybe we should change the name to "Select option" and redirect to product page?

**Comment by maximebiloe** [comment]
For products with attributes, we choose to not display the add to cart button. It's a bug that we see it.

**Comment by maximebiloe** [comment]
I've made the modification here: https://github.com/PrestaShop/PrestaShop/pull/6605

Thanks!
