### ISSUE TITLE
.htaccess anyone?

### ISSUE THREAD

**Issue by pwnsdx** [PrestaShop/StarterTheme#169]
Hello,

Many files should be restricted from being seen in the browser such as:

http://fo.demo.prestashop.com/themes/classic/config/theme.yml
http://fo.demo.prestashop.com/themes/classic/_dev/webpack.config.js

Regards,

**Comment by MitsuhaKitsune** [comment]
The _dev directory shouldn't be on production enviroment

**Comment by PierreRambaud** [comment]
This project is not maintained anymore by the core team. Theme improvements must be brought instead to the classic theme in the [PrestaShop repository](https://github.com/PrestaShop/PrestaShop).
Thanks for your understanding.
