### ISSUE TITLE
{widget_block} doesn't work

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/StarterTheme#171]
We cannot use `{widget_block}` feature, we have an error saying:
`Warning: Missing argument 1 for Ps_Linklist::getWidgetVariables()`

**Comment by aleeks** [comment]
Hello @kpodemski,
Thank you for report!

ping @julienbourdeau

**Comment by kpodemski** [comment]
@aleeks @julienbourdeau we should have:
https://github.com/PrestaShop/PrestaShop/blob/develop/config/smartyfront.config.inc.php#L127

`null, $params` there

**Comment by xBorderie** [comment]
Do you think you can do a PR?

**Comment by aleeks** [comment]
Thank you @kpodemski !
