### ISSUE TITLE
Theme core.js uses class names to update the product page.

### ISSUE THREAD

**Issue by haveyougotanypets** [PrestaShop/StarterTheme#175]
This is a duplication of the bug I have filed for your main dev for 1.7:

http://forge.prestashop.com/browse/BOOM-2480

Please add code comments to any section of the starter theme where css class names are used by the core.js to make changes to the DOM. For example:

<div class="images-container"> in product-cover-thumbnails.tpl

**Comment by PierreRambaud** [comment]
This project is not maintained anymore by the core team. Theme improvements must be brought instead to the classic theme in the [PrestaShop repository](https://github.com/PrestaShop/PrestaShop).
Thanks for your understanding.
