### ISSUE TITLE
Call custom script after _prestashop2['default'].emit('updateProduct'

### ISSUE THREAD

**Issue by BluTiGeS** [PrestaShop/StarterTheme#177]
Hello there,

I wanted to call a special script if the updateProduct was emitted.
But how can I connect to the event in another modules .js file?

Is this possible or can it be made possible?

I thought it wul work this way:
$(document).on(   'updateProduct',function(){doMyStuffAfterProdUpdate();});

But it never get called so i assume i have wrong scope.

Please help. THX

**Comment by kpodemski** [comment]
`prestashop.on('updateProduct', callback);`

**Comment by BluTiGeS** [comment]
Thanks, worked ;)

**Comment by JohanRodas** [comment]
You can use 'updatedProduct'.
prestashop.on('updatedProduct', callback);
