### ISSUE TITLE
Fix Cancel URL in address-form.tpl

### ISSUE THREAD

**Issue by haveyougotanypets** [PrestaShop/StarterTheme#178]
Issue:
/templates/checkout/_partials/address-form.tpl
Current URL cancel address link redirects to home page rather than staying on the checkout page.

Fix:
Changeurl on line 27 and line 31 from:
`<a href="?cancelAddress={$type}">`

To:
`<a href="{$urls.pages.order}&cancelAddress={$type}">`

This also effects the classic theme.

**Comment by xBorderie** [comment]
Could you directly make a pull request with your fix?
Thank you!

**Comment by vavrecan** [comment]
https://github.com/PrestaShop/StarterTheme/pull/180

**Comment by PierreRambaud** [comment]
This project is not maintained anymore by the core team. Theme improvements must be brought instead to the classic theme in the [PrestaShop repository](https://github.com/PrestaShop/PrestaShop).
Thanks for your understanding.
