### ISSUE TITLE
Theme installation

### ISSUE THREAD

**Issue by prestanesia** [PrestaShop/StarterTheme#19]
I have succesfully followed step 1 - 3 and PrestaShop 1.7 is installed. Bit confuse on step 4, how do I activate the Starter Theme ? as it doesnt show in Preferences - Themes.

**Comment by maximebiloe** [comment]
Hello,

Did you switch to `feat/starter-theme branch` in your PrestaShop repo ?
When you've done that, you should see the StarterTheme into your `Preferences > Themes` tab.

Regards.

**Comment by prestanesia** [comment]
yes, i switched to `feat/starter-theme` branch and do install from there.

**Comment by maximebiloe** [comment]
Take a look at this commit : https://github.com/PrestaShop/PrestaShop/commit/8feb2dddde4ce8ca9b7e1a928195dd43bf96d3ef

This is a script which automatically set up your environment.

**Comment by prestanesia** [comment]
will check.

Thanks !

**Comment by prestanesia** [comment]
sorry. its runing now, the setup-workspace is definitely helpful.

Thanks !
