### ISSUE TITLE
[ThemeRepository] Theme configuration file not found for theme at ...

### ISSUE THREAD

**Issue by dunets** [PrestaShop/StarterTheme#192]
When I try to use a starter theme, I see the next error exception:
![image](https://cloud.githubusercontent.com/assets/6217617/26409856/a5d2c8f6-4099-11e7-85b0-11768945e386.png)
According to the [documentation](http://developers.prestashop.com/themes/gettingstarted/index.html#create-your-theme-yml-file) I only need to create a folder, paste the files, and rename `theme.dist.yml` and I did this

**Comment by aleeks** [comment]
Hello @dunets 
Are you sure your theme.yml is in the good folder ?

**Comment by dunets** [comment]
Hi @aleeks , I think yes... 
![image](https://cloud.githubusercontent.com/assets/6217617/26410428/2d7473a8-409b-11e7-9c45-6089fcb34785.png)

**Comment by dunets** [comment]
@

**Comment by haroun-scred** [comment]
Hi @dunets , the same for me... can you explain?

**Comment by zolv** [comment]
@dunets Can You explain what needs to be done?
I just follow steps in the [tutorial](http://doc.prestashop.com/display/PS17/Getting+started+with+theme+development#Gettingstartedwiththemedevelopment-CreateyourthemefromtheStarterTheme) and I get the same error.

It looks like there is some caching(?) which doesn't see any further changes in `theme.yml` and still thinks that theme's name is `StarterTheme `and looks for such a directory in `/themes` (which doesn't exist).

I checked the link to install the theme in backoffice and it looks like this:
`http://192.168.0.105/prestashop/admin/index.php?controller=AdminThemes&token=[token]&action=enableTheme&theme_name=StarterTheme`
If I change the param `theme_name` to my theme name (theme's directory name) it is installed properly.

**Comment by Nayar** [comment]
Having this same issue. How to clear the cache or something?

**Comment by magyk111** [comment]
Problem is beacause you rename directory in themes. The name directory is exactli witch name theme.yml

**Comment by magyk111** [comment]
go to config/theme.yml >>>>edit >>>>and the first row is name of the directory

**Comment by gomonkey** [comment]
Have the same issue, in my theme.yml in the first row there is the folder's name.
In admin, still looking for StarterTheme and missing preview, because doesn't find the folder.
I am installed by ssh and follow the steps in the tutorial.
I try to clean cache too, but still have the issue.

**Comment by gomonkey** [comment]
**How I solved:**

After click on "use this theme" button and have error, I just change **theme_name=StarterTheme** with MyThemeName, from the bar and is work and then press enter

`https://.......&action=enableTheme&theme_name=StarterTheme`

After that, was install correctly and I try to switch with  the classic one and my theme was there ready to install again.
