### ISSUE TITLE
Theme not loading the styles.css 

### ISSUE THREAD

**Issue by aleixpellicer** [PrestaShop/StarterTheme#193]
We have configured the npm, and have done the npm run watch, but styles are not being loaded in the theme. We have also tried adding them in theme.yml but it does not work either.

We feel this should be working by default but apparently it is not.

**Comment by Parser-Error** [comment]
you can clear cache on prestashop and start cmd in _dev : webpack --watch -d

**Comment by PierreRambaud** [comment]
This project is not maintained anymore by the core team. Theme improvements must be brought instead to the classic theme in the [PrestaShop repository](https://github.com/PrestaShop/PrestaShop).
Thanks for your understanding.
