### ISSUE TITLE
Modules Data / JS not initialized?

### ISSUE THREAD

**Issue by lucacattide** [PrestaShop/StarterTheme#194]
Hi everyone, I'm newbie in Prestashop development.
I just installed on my localhost the CMS and downloaded the starter theme. I'm following step by step the guide. I've been able to edit some of the front-end templates, styles, and so on.
But from a few days i'm stuck on the modules part. 
I'm trying to put some of them on my template pages (like image slider, custom text blocks, etc.), with the 1.7 new function {widget_block}, in order to override some html nodes and align them to my custom css. HTML and styles are ok and works well. The module is being included in front-end but there's 2 main errors:

1) Data binding: it seems that with this Smarty helper, but with the normal "hooks" way, the data updated in the DB are not shown in the front-end side of the module. I.E. for the custom block, I edit the text; the module is included right with ```{widget_block}``` but the text is still the demo one. So not any kind of dynamic rendering;

2) Modules JS is not working: As well as other modules, such as imageslider, they're not working. I read about that jquery is now included in ```core.js```, and it works with my custom code. Very well. But the modules are totally broken, as well as they're not initialized after all (I see the correct styled front-end template, but no JS running on it). From the guide there's not any indication about the need of the modules/plugins initialization - on template side, but I'm suspecting that is really required. Now, I'm digging inside the classic theme, to identify some snippet about that, with no success. Seems that there's not trace of some sort of initialization in its own ```theme.js```, for external plugins apart. 

So, why classic works and the starter not? I really need to initialize modules in my custom ```theme.js```?

What I'm missing?

Thanks in advance everybody.

**Comment by lucacattide** [comment]
**UPDATE**

Related to point 1:

- Just found a misconfiguration in my system cache, so that's solved;

Still looking for a solution about point 2.

**Comment by lucacattide** [comment]
**UPDATE 2**

So, finally I solved my problem. 
Simply, modules are being installed in some specified hooks, defined in their ```install()``` controller function. I was putting those modules without defining their position in their available hook.

In this particular case and for the future, I strongly recommend you to update the official guide, by specifying this aspect, because until today I was totally confused and stuck at this point of development. Especially for those, like me, are not experienced in it, neither come from previous versions of the platform. 
I'm starting using PrestaShop from 1.7.1.x with StarterTheme, and this is not explained there.

Now, I'm still using the ```{widget}/{widget_block}``` helper, but also specifying the destination hook in my ```theme.yml``` file. If I need to replace entirely the spot with another  hook or in a custom one, I'm overriding the module controller as explained [in this article](http://build.prestashop.com/howtos/module/how-to-override-modules/).

**Comment by PierreRambaud** [comment]
This project is not maintained anymore by the core team. Theme improvements must be brought instead to the classic theme in the [PrestaShop repository](https://github.com/PrestaShop/PrestaShop).
Thanks for your understanding.
