### ISSUE TITLE
Publish the repository as a Composer package

### ISSUE THREAD

**Issue by gskema** [PrestaShop/StarterTheme#2]
I recently discovered that it's possible to make a custom installer for a package, which installs package to a custom directory. After a little browsing, I even found that there's already an installer for PrestaShop:
[composer/installers](https://github.com/composer/installers/blob/master/src/Composer/Installers/PrestashopInstaller.php)

I assume that you guys already know about this since I saw you have been doing this for core module.

I was hoping that maybe we could publish this theme as a composer module. To do so, we should probably rename the package to lowercase, since it is gonna reside in `themes/startertheme/*`.

What do you think?

**Comment by julienbourdeau** [comment]
I thought about it but I don't think it will make sense for the starter theme.

The point of a external package managed with composer is that composer will make sure you have the right version and take care of the updates.

The way we see the starter theme is that you create your own git repository for your next theme, you copy and paste the latest stable release of this starter theme and begin modifying straight away. You will never need to (or be able to) update it.

Nevertheless, our new default theme could be a package. Especially if it's used as a parent theme.

Maybe I'm wrong tho, **I would like to hear more opinions about this**.

**Comment by ZiZuu-store** [comment]
@jeromenadaud I think it could be configured as a dev requirement of the "child" themes ... so I agree in including a composer.json file in the theme

**Comment by gskema** [comment]
I think the workflow holds the answer here. When you clone a theme repo:
- the original .git stays inside the folder
- it may mess up the project repository (for people who work with whole shop) by committing a submodule
- you may want to edit what you cloned right away and establish your own repo in this folder

Other workflows I see:
- composer require, edit what you downloaded
- composer require, copy the files manually, perhaps update the package from time to time and check the docs (which you cleaned up in your own theme)
- composer require, create a new theme using PrestaShop (copy)

**Comment by ZiZuu-store** [comment]
AFAICS this repo should only used from themes' developers .. so I suppose that is will be used as a dev require by the reale theme

**Comment by julienbourdeau** [comment]
I'll close this issue since we moved the starter theme inside PrestaShop/PrestaShop.
