### ISSUE TITLE
Webpack erase js with css

### ISSUE THREAD

**Issue by gnujeremie** [PrestaShop/StarterTheme#208]
In ```_dev/webpack.config.js```, line 65-68 : 
```
  output: {
    path: '../assets/js',
    filename: 'theme.js'
},
```

Should be

```
  output: {
    path: '../assets/css',
    filename: 'theme.css'
},
```

**Comment by xBorderie** [comment]
Would you like to create a PR for this change? :)

**Comment by Parser-Error** [comment]
why ?

**Comment by gnujeremie** [comment]
Because this part is for the css compilation. If you let it this way, when you update you scss files it erases the built js files.

**Comment by Parser-Error** [comment]
Yes ok thank you !

**Comment by PierreRambaud** [comment]
This project is not maintained anymore by the core team. Theme improvements must be brought instead to the classic theme in the [PrestaShop repository](https://github.com/PrestaShop/PrestaShop).
Thanks for your understanding.
