### ISSUE TITLE
Ajax cart / quantity update issue - Need JS

### ISSUE THREAD

**Issue by d4vv** [PrestaShop/StarterTheme#214]
Hello. I started using Starter theme (sass / susy / flex mostly) and it really works as I want expect few things... one of them is for example cart (when I want to update the produt quantity, it adds the url to the search bar[which shouldn't happend]). I guess it's because of javascripts... maybe somebody would have an idea what can I do with javascripts? Or at least which component from classic theme should I implement here?

**Comment by PierreRambaud** [comment]
This project is not maintained anymore by the core team. Theme improvements must be brought instead to the classic theme in the [PrestaShop repository](https://github.com/PrestaShop/PrestaShop).
Thanks for your understanding.
