### ISSUE TITLE
How to add an asset like Bootsrap

### ISSUE THREAD

**Issue by Lospepes** [PrestaShop/StarterTheme#215]
#I'm a newbie to Node/NPM/Webpack/Prestashop technologies. I'm trying to create a theme with your Starter Theme and add Bootstrap and other libraries.

For the CSS I do it this way, I don't know if it's good:

theme.scss : 
@import "../node_modules/bootstrap/scss/bootstrap";

But for javascript files, I dont't find, I tried many ways, I have problems with UglifyJs among others. I tried import, require,... in theme.js or directly in the entry of webpack.config.js

Would you be able to give me a step to follow to add css files and javascripts files to the Starter Theme and use all the tools you provided  please?

**Comment by Parser-Error** [comment]
in : Prestashop/themes/YOUR_THEME/_dev/ there are a : webpack.config.js line 59 there are : 
  entry: [
    './css/normalize.css',
    './css/example.less',
    './css/st/dev.styl',
    './css/theme.scss'
  ],
 you add the file bootstrap in : Prestashop/themes/YOUR_THEME/_dev/css 
after add the line : './css/bootstrap.min.css', (don't forget comma)

save and restart webpack !!!! enjoy!!!

**Comment by Lospepes** [comment]
Hello,

Thanks for your answer, I didn't have any problems with the CSS. 

With the JS, I had problems. I tested several different ways:

require('bootstrap');
in _dev/js/theme.js

Or : 

 // JavaScript
  entry: [
    './js/bootstrap.min.js',
    './js/theme.js'
  ], 
at ligne 35 webpack.config.js

In these 2 examples I have a UglifyJS compilation warning.

![img_22012018_105644_0](https://user-images.githubusercontent.com/1099230/35215637-286ef4bc-ff65-11e7-9dff-aad13c390f1c.png)

And for the other tests, I had some compilation errors so I don't think they are viable at all.

Thank you for your help.

**Comment by Parser-Error** [comment]
save your boostrap in folder : asset/js of your theme and add this in webpack

 output: {
    path: '../assets/js',
    filename: 'theme.js'
    filename: 'bootstrap.js'
  },

**Comment by db306** [comment]
I've done it this way:

`package.json`

"devDependencies": {
        "babel-core": "^6.4.5",
        "babel-loader": "^6.2.1",
        "babel-preset-es2015": "^6.3.13",
        "css-loader": "^0.23.1",
        "exports-loader": "^0.6.3",
        "expose-loader": "^0.7.1",
        "extract-text-webpack-plugin": "^1.0.1",
        "file-loader": "^0.8.5",
        "imports-loader": "^0.6.5",
        "less": "^2.7.1",
        "less-loader": "^2.2.3",
        "node-sass": "^3.7",
        "postcss-loader": "^0.8.0",
        "sass-loader": "^3.1.2",
        "style-loader": "^0.13.0",
        "stylus": "^0.54.5",
        "stylus-loader": "^2.1.2",
        "webpack": "^1.13.1",
        "bootstrap": "^4.0.0",
        "jquery": "^3.3.1",
        "popper.js": "^1.12.9"
    }

`webpack.config.js`

entry: [
        './js/theme.js',
        './node_modules/bootstrap/dist/js/bootstrap.bundle.js',
    ],

// CSS
entry: [
        './node_modules/bootstrap/dist/css/bootstrap.css',
        './css/normalize.css',
        './css/example.less',
        './css/st/dev.styl',
        './css/theme.scss'
    ],

I wonder whether this actually makes sense or if I should have it as stated above ... meh

**Comment by db306** [comment]
Meh,
I think the best way is @Parser-Error although compiling with the sass version so you can make your own bootstrap theme along the way.

entry: [
        './css/bootstrap/bootstrap.scss',
        './css/normalize.css',
        './css/example.less',
        './css/st/dev.styl',
        './css/theme.scss'
    ],

entry: [
'./js/theme.js',
'./node_modules/bootstrap/dist/js/bootstrap.bundle.js',
],

**Comment by comxd** [comment]
jQuery already included into the Prestashop core JS files. Here my working version for work with Bootstrap 4 without red.

theme.js:
```
require('bootstrap');
require('../css/theme.scss');

$(function () {
    // DOM READY
});
```

webpack.config.js:

```
var webpack = require('webpack');
var ExtractTextPlugin = require("extract-text-webpack-plugin");

var plugins = [];

plugins.push(
  new ExtractTextPlugin('../css/theme.css')
);

module.exports = [{
  // JavaScript
  entry: [
    './js/theme.js',
  ],
  output: {
    path: '../assets/js',
    filename: 'theme.js'
  },
  module: {
    loaders:  [{
      test: /\.js$/,
      exclude: /node_modules/,
      loaders: ['babel-loader']
    }, {
      test: /\.scss$/,
      loader: ExtractTextPlugin.extract(
          "style",
          "css-loader?sourceMap!postcss!sass-loader?sourceMap"
      )
    }, {
      test: /\.styl$/,
      loader: ExtractTextPlugin.extract(
          "style",
          "css-loader?sourceMap!postcss!stylus-loader?sourceMap"
      )
    }, {
      test: /\.less$/,
      loader: ExtractTextPlugin.extract(
          "style",
          "css-loader?sourceMap!postcss!less-loader?sourceMap"
      )
    }, {
      test: /\.css$/,
      loader: ExtractTextPlugin.extract(
          'style',
          'css-loader?sourceMap!postcss-loader'
      )
    }, {
      test: /.(png|woff(2)?|eot|ttf|svg|jpg)(\?[a-z0-9=\.]+)?$/,
      loader: 'file-loader?name=../css/[hash].[ext]'
    }]
  },
  externals: {
    prestashop: 'prestashop',
    jquery: 'jQuery'
  },
  plugins: plugins,
  resolve: {
    extensions: ['', '.js', '.scss', '.styl', '.less', '.css']
  }
}];

```

**Comment by PierreRambaud** [comment]
This project is not maintained anymore by the core team. Theme improvements must be brought instead to the classic theme in the [PrestaShop repository](https://github.com/PrestaShop/PrestaShop).
Thanks for your understanding.
