### ISSUE TITLE
Theme only avaliable for prestashop 1.7

### ISSUE THREAD

**Issue by debzar** [PrestaShop/StarterTheme#227]
I'm trying to install this theme and I get the following error:
"This theme is only for prestashop 1.7"
Currently I have prestashop 1.7.2.5 installed.

**Comment by Almusamim** [comment]
why maintaining and keeping the starter theme up to date is totally dead? :(

**Comment by nevaljawko** [comment]
**Step 1: create theme.yml**
First of all, you need to rename config/theme.dist.yml to config/theme.yml and edit it according to your theme name.

**Comment by PierreRambaud** [comment]
This project is not maintained anymore by the core team. Theme improvements must be brought instead to the classic theme in the [PrestaShop repository](https://github.com/PrestaShop/PrestaShop).
Thanks for your understanding.
