### ISSUE TITLE
Any plans to update Boostrap?

### ISSUE THREAD

**Issue by PrestaShark** [PrestaShop/StarterTheme#235]
Hi guys.
Currently classic theme use Bootstrap v4.0.0-alpha.5 which is very old (literally two years...)
Any roadmaps for v4.1.x update?

**Comment by khouloudbelguith** [comment]
Hi @PrestaShark,

@prestarocket released a port of Classic to Bootstrap 4.1, which you can find here: https://github.com/PrestaShop/classic-rocket
Thanks!
