### ISSUE TITLE
Feature Request - Add multiple predefined color.

### ISSUE THREAD

**Issue by By-oussef** [PrestaShop/StarterTheme#236]
currently the theme is founit with pretty simple colors: blue, white and gray. It would be interesting to add several shades of colors modifiable from the backend. Because all users do not have the same tastes. Some prefer soft colors others brighter and brighter colors others darker.

**Comment by PierreRambaud** [comment]
This project is not maintained anymore by the core team. Theme improvements must be brought instead to the classic theme in the [PrestaShop repository](https://github.com/PrestaShop/PrestaShop).
Thanks for your understanding.
