### ISSUE TITLE
| Bug | in the menu bar when there are multiple categories

### ISSUE THREAD

**Issue by By-oussef** [PrestaShop/StarterTheme#237]
Bug in the menu bar when there are several categories. The search bar is not visible correctly.
![zenphoto](https://user-images.githubusercontent.com/41373170/50539587-30459a80-0b83-11e9-9809-65d9b859d5d7.jpg)

**Comment by SharakPL** [comment]
It's not a bug. You're just missing some proper styling. Besides it has nothing to do with Starter Theme because you're using Classic theme that is installed by default for each new store.

**Comment by PierreRambaud** [comment]
This project is not maintained anymore by the core team. Theme improvements must be brought instead to the classic theme in the [PrestaShop repository](https://github.com/PrestaShop/PrestaShop).
Thanks for your understanding.
