### ISSUE TITLE
Faceted search search_filter_controls

### ISSUE THREAD

**Issue by vincent-dp** [PrestaShop/StarterTheme#242]
The module folder is empty, so most of the 'standard' modules doesn't show up (visualy)
and even if you create a tpl for (let say) ps_facetedsearch, the module will not work, because theme.js is empty

It's ok, since it's not the purpose of starterTheme. But, where can I find the information about what code I need in theme.js to make one or another prestashop basic modules to work?

**Comment by PierreRambaud** [comment]
This project is not maintained anymore by the core team. Theme improvements must be brought instead to the classic theme in the [PrestaShop repository](https://github.com/PrestaShop/PrestaShop).
Thanks for your understanding.
