### ISSUE TITLE
product-miniature.tpl doesn't exist

### ISSUE THREAD

**Issue by ludohenin** [PrestaShop/StarterTheme#82]
Out the box the theme throws an error due to the lack of `templates/catalog/product-miniature.tpl` file.
This file is expected by `ps_featuredproducts ` module.
Looking at the Classic theme, this module template is overriden, several questions comes to my mind:
* should the starter theme implement override ? (I don't think so)
* should the product miniature template file be present in the starter theme ? (I don't think so)
* why a re-rewritten module rely on an "already" obsolete theme implementation ?

by the way, in `templates/catalog/_partials/miniatures/product.tpl` it seems that `$product.flags` has been renamed `$product.labels`

**Comment by maximebiloe** [comment]
Hello,

If look here:https://github.com/PrestaShop/ps_featuredproducts/blob/master/views/templates/hook/ps_featuredproducts.tpl#L5 we have fixed this 24 days ago.
I think you don't have the latest changes. You can make a `git pull` on both `PrestaShop` and `StarterTheme` and also make a `composer update` to get the latest modules version.

As we're still in a beta phase, it may have a little delay between changed on `PrestaShop` and `StarterTheme` synchronization.

Regards
