### ISSUE TITLE
blockcart: widget display error

### ISSUE THREAD

**Issue by ludohenin** [PrestaShop/StarterTheme#85]
When using `blockcart` as a widget `{widget name="blockcart" hook="displayNav"}` I get an undefined index cart.
I solved the issue by changing this line https://github.com/PrestaShop/blockcart/blob/feat/starter-theme/blockcart.php#L74 setting cart from the context. Not sure this the correct way to do that though.

Let me know if this a viable solution, so I'll make a PR.

**Comment by maximebiloe** [comment]
Thanks for reporting this!

If the `$params['cart']` is set, we should take this one.
So, I would replace [this line](https://github.com/PrestaShop/blockcart/blob/feat/starter-theme/blockcart.php#L74) by `'cart' => (new CartPresenter)->present(isset($params['cart']) ? $params['cart'] : $this->context->cart)`.

Can you make a PR yo do that, please?

Regards

**Comment by ludohenin** [comment]
ok, will submit a PR today.

**Comment by julienbourdeau** [comment]
Closed by https://github.com/PrestaShop/ps_shoppingcart/commit/b952d42b7654746c6a40337fc786906f4abb6d2d
Thanks @ludohenin
